name: GitHub release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Binaries:
    runs-on: ${{ matrix.os }}
    outputs:
      version-tag: ${{ steps.version_tag.outputs.VERSION_TAG }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            arch: x86
          - os: windows-2019
            arch: x64
          - os: macos-13
            arch: x64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: ${{ matrix.arch }}

      - name: Install PyInstaller
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller --noconfirm --clean tdmgr.spec

      - name: Create Mac .dmg
        if: matrix.os == 'macos-13'
        shell: bash
        run: |
          brew install create-dmg
          newfile=$(basename *.app .app).dmg
          create-dmg "dist/$newfile" dist
          rm dist/*.app

      - name: Upload binaries artifact to workflow
        uses: actions/upload-artifact@v3
        with:
          name: binaries_build
          path: dist/*


  Draft-Release:
    runs-on: ubuntu-latest
    needs: Binaries
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Download artifacts from build
        uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries_build/*
          tag_name: 0.3
          draft: true
          prerelease: true
          generate_release_notes: true
          name: "TDM asdqwe"
